"""
Advent of Code 2022
Adam Pletcher
adam.pletcher@gmail.com

--- Day 9: Rope Bridge ---
This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river 
far below you.

You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; 
maybe you can even figure out where not to step.

Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far 
enough away from the tail, the tail is pulled toward the head.

Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a 
two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you 
can determine how the tail will move.

Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must 
always be touching (diagonally adjacent and even overlapping both count as touching):

....
.TH.
....

....
.H..
..T.
....

...
.H. (H covers T)
...

If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in 
that direction so it remains close enough:

.....    .....    .....
.TH.. -> .T.H. -> ..TH.
.....    .....    .....

...    ...    ...
.T.    .T.    ...
.H. -> ... -> .T.
...    .H.    .H.
...    ...    ...

Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step 
diagonally to keep up:

.....    .....    .....
.....    ..H..    ..H..
..H.. -> ..... -> ..T..
.T...    .T...    .....
.....    .....    .....

.....    .....    .....
.....    .....    .....
..H.. -> ...H. -> ..TH.
.T...    .T...    .....
.....    .....    .....

You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail 
both start at the same position, overlapping.

For example:

R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2

This series of motions moves the head right four steps, then up four steps, then left three steps, then down one 
step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no 
longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a 
reference point):

== Initial State ==

......
......
......
......
H.....  (H covers T, s)

== R 4 ==

......
......
......
......
TH....  (T covers s)

......
......
......
......
sTH...

......
......
......
......
s.TH..

......
......
......
......
s..TH.

== U 4 ==

......
......
......
....H.
s..T..

......
......
....H.
....T.
s.....

......
....H.
....T.
......
s.....

....H.
....T.
......
......
s.....

== L 3 ==

...H..
....T.
......
......
s.....

..HT..
......
......
......
s.....

.HT...
......
......
......
s.....

== D 1 ==

..T...
.H....
......
......
s.....

== R 4 ==

..T...
..H...
......
......
s.....

..T...
...H..
......
......
s.....

......
...TH.
......
......
s.....

......
....TH
......
......
s.....

== D 1 ==

......
....T.
.....H
......
s.....

== L 5 ==

......
....T.
....H.
......
s.....

......
....T.
...H..
......
s.....

......
......
..HT..
......
s.....

......
......
.HT...
......
s.....

......
......
HT....
......
s.....

== R 2 ==

......
......
.H....  (H covers T)
......
s.....

......
......
.TH...
......
s.....

After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, 
s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

..##..
...##.
.####.
....#.
s###..

So, there are 13 positions the tail visited at least once.

Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?
"""

import numpy


class Point2:
	def __init__(self, x, y):
		self.x = x
		self.y = y
		
	def __repr__(self):
		return '<Point2 ({0},{1})>'.format(self.x, self.y)
		

def parse_input() -> list:
	data = [ ]
	
	for line in open('input.txt', 'r'):
		direction, distance = line.strip().split(' ')
		distance = int(distance)

		data.append((direction, distance))
		
	return data


def print_board(h_pos, t_pos):
	# Create grid
	grid = []

	for y in range(5):
		row = [ ]
		for i in range(6):
			row.append('.')

		grid.append(row)
		
	grid[4][0] = 's'
	grid[t_pos.y][t_pos.x] = 'T'
	grid[h_pos.y][h_pos.x] = 'H'
	
	for row in grid:
		print(''.join(row))

	print('')

		

def move_tail(h_pos, t_pos):
	# Move the tail position towards the head position.
	# But only if distance between them is > 1
	if abs(h_pos.x - t_pos.x) <= 1 and abs(h_pos.y - t_pos.y) <= 1:
		return t_pos
	
	if t_pos.x < h_pos.x:
		t_pos.x += 1
	elif t_pos.x > h_pos.x:
		t_pos.x -= 1

	if t_pos.y < h_pos.y:
		t_pos.y += 1
	elif t_pos.y > h_pos.y:
		t_pos.y -= 1
		
	return t_pos
	

if __name__ == '__main__':
	data = parse_input()
	
	h_pos = Point2(0,4)
	t_pos = Point2(0,4)
	
	tail_positions = [ ]
	
	#print_board(h_pos, t_pos)
	
	# Move the head knot
	for move in data:
		h_dir, h_dist = move
		
		for i in range(h_dist):
			if h_dir == 'U':
				h_pos.y -= 1
			elif h_dir == 'R':
				h_pos.x += 1
			elif h_dir == 'D':
				h_pos.y += 1
			else:
				h_pos.x -= 1
			
			# Move tail to match new head pos, if needed
			t_pos = move_tail(h_pos, t_pos)
		
			# Add to list of visited locations
			tail_positions.append((t_pos.x, t_pos.y))

		#print_board(h_pos, t_pos)

	unique_positions = set(tail_positions)	
	print('answer =', len(unique_positions))
